CREATE TABLE Gashub (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CompanyID VARCHAR(50) NOT NULL UNIQUE,
    CompanyName TEXT,
    MailAddress1 TEXT,
    MailAddress2 TEXT,
    MailCity TEXT,
    MailState TEXT,
    MailZip TEXT,
    MailCountry TEXT,
    ShipAddress1 TEXT,
    ShipAddress2 TEXT,
    ShipCity TEXT,
    ShipState TEXT,
    ShipZip TEXT,
    ShipCountry TEXT,
    GLAccount VARCHAR(50),
    SubAccount VARCHAR(50),
    CompanyPhone VARCHAR(20),
    CompanyFax VARCHAR(20),
    CompanyEmail VARCHAR(100),
    CompanyCare TEXT,
    Description TEXT,
    GasTicker TEXT NOT NULL UNIQUE
);
